### ISSUE TITLE
Feedback on draft-thomson-hybi-http-timeout-00

### ISSUE THREAD

**Issue by zerkms** [martinthomson/empty-draft#1]
Hi Martin,

my apologies for creating an issue in this repository but I could not find a better way contact you :-)

I've been researching a question of "cooperative" http timeouts in distributed systems (which is almost everything now in 2023), to adopt in my server- and client- applications. Just to find out that it literally was only one `draft-thomson-hybi-http-timeout-00` (preceded by `draft-loreto-http-timeout-00`) ever published, with no active (or at all?) discussion around it.

It's pity the community didn't decide to follow along.

Nonetheless, it very well aligns with my opinion on how to negotiate timeouts too, so I think I will just be using the `request-timeout` header in my software :-)

Thanks for the draft and your work with standards in general, and sorry again for publishing this message here.

**Comment by martinthomson** [comment]
My email is in the draft, try that.

You might like to look at https://www.rfc-editor.org/rfc/rfc7240#section-4.3 which is the successor of those early ideas.
